/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2018-01-30 05:01:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class inserttour_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/front.jsp", Long.valueOf(1517240878480L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/front.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"home\">\r\n");
      out.write("\t\t\t");

				if (session.getAttribute("name").equals("admin")) {
			
      out.write("\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"home.jsp\" class=\"form-button-home\">\r\n");
      out.write("\t\t\t\t<input class=\"button-add\" type=\"submit\" name=\"link\" value=\"Home\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t");

				} else if (session.getAttribute("name").equals("user")) {
			
      out.write("<form method=\"post\" action=\"userhome.jsp\" class=\"form-button-home\">\r\n");
      out.write("\t\t\t\t<input class=\"button-add\" type=\"submit\" name=\"link\" value=\"Home\">\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li class=\"drop\"><div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t<button class=\"dropbtn\">Add Data</button>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"inserttour.jsp\" class=\"form-button\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"button-add\" type=\"submit\" name=\"link\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"Tournament\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"insertplayer.jsp\" class=\"form-button\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"button-add\" type=\"submit\" name=\"link\" value=\"Player\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"ListServlet\" class=\"form-button\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"button-add\" type=\"submit\" name=\"link\" value=\"Match\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"retrieve\"><form method=\"post\"\r\n");
      out.write("\t\t\t\taction=\"RetrievePlayerServlet\" class=\"form-button\">\r\n");
      out.write("\t\t\t\t<input class=\"button-add\" type=\"submit\" value=\"Retrieve Players\">\r\n");
      out.write("\t\t\t</form></li>\r\n");
      out.write("\t\t<li class=\"drop\"><div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t<button class=\"dropbtn\">Retrieve Data</button>\r\n");
      out.write("\t\t\t\t<div class=\"dropdown-content\">\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"RetrieveMatchServlet\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-button\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"button-add\" type=\"submit\" value=\"Match\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"ListServlet\" class=\"form-button-match\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"button-add\" type=\"submit\" name=\"link\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"Player vs Player\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" action=\"ListServlet\" class=\"form-button-match\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"button-add\" type=\"submit\" name=\"link\"\r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"Player in Tournament\">\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t<li class=\"logout\"><form method=\"post\" action=\"LogoutServlet\"\r\n");
      out.write("\t\t\t\tclass=\"form-button\">\r\n");
      out.write("\t\t\t\t<input class=\"button-add\" type=\"submit\" value=\"Logout\">\r\n");
      out.write("\t\t\t</form></li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Add a Tournament</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/insertpage.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/button-style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("\t<form method=\"post\" action=\"InsertTournamentServlet\" class=\"insert-form\"\r\n");
      out.write("\t\tonsubmit=\"return validateForm()\">\r\n");
      out.write("\t\t<h2>Add a Tournament</h2>\r\n");
      out.write("\t\t<input type=\"text\" name=\"tourname\" id=\"tourname\"\r\n");
      out.write("\t\t\tplaceholder=\"Tournament Name\" /> <br>\r\n");
      out.write("\t\t<input class=\"submitButton\" type=\"submit\" value=\"Add Tournament\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<script src=\"js/validateinserttour.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
