/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2018-01-25 10:16:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.zilker.properties.ReadFromPropertiesFile;
import java.util.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Priyamvada%20Mukund/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Tournament/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1516618636542L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.zilker.properties.ReadFromPropertiesFile");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/styles.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/button-style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/home.css\">\r\n");
      out.write("<title>Home</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"blink();\">\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h1>Home Page</h1>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t<h2 id=\"head\">\r\n");
      out.write("\t\tWelcome\r\n");
      out.write("\t\t");

		out.println(ReadFromPropertiesFile.getProperties("admin"));
	
      out.write("\r\n");
      out.write("\t</h2>\r\n");
      out.write("\t<form method=\"post\" action=\"insertmatch.jsp\"\r\n");
      out.write("\t\tclass=\"form-navigate insert\">\r\n");
      out.write("\t\t<input class=\"navigate\" type=\"submit\" value=\"Insert Match\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<form method=\"post\" action=\"../RetrievePlayerServlet\"\r\n");
      out.write("\t\tclass=\"form-navigate player\">\r\n");
      out.write("\t\t<input class=\"navigate\" type=\"submit\" value=\"Retrieve Players\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<form method=\"post\" action=\"../RetrieveMatchServlet\"\r\n");
      out.write("\t\tclass=\"form-navigate match\">\r\n");
      out.write("\t\t<input class=\"navigate\" type=\"submit\" value=\"Retrieve Matches\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<form method=\"post\" action=\"../MostImprovedServlet\"\r\n");
      out.write("\t\tclass=\"form-navigate improve\">\r\n");
      out.write("\t\t<input class=\"navigate\" type=\"submit\"\r\n");
      out.write("\t\t\tvalue=\"Find Most Improved Player\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<form method=\"post\" action=\"playermatch.jsp\"\r\n");
      out.write("\t\tclass=\"form-navigate player-match\">\r\n");
      out.write("\t\t<input class=\"navigate\" type=\"submit\" value=\"Find Matches of a Player\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<form method=\"post\" action=\"twoplayermatch.jsp\"\r\n");
      out.write("\t\tclass=\"form-navigate players\">\r\n");
      out.write("\t\t<input class=\"navigate\" type=\"submit\"\r\n");
      out.write("\t\t\tvalue=\"Find Matches between Players\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<form method=\"post\" action=\"playertour.jsp\" class=\"form-navigate tour\">\r\n");
      out.write("\t\t<input class=\"navigate\" type=\"submit\"\r\n");
      out.write("\t\t\tvalue=\"Find Player Results in Tournament\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<form method=\"post\" action=\"../LogoutServlet\" class=\"button-form-logout\">\r\n");
      out.write("\t\t<input class=\"logoutButton\" type=\"submit\" value=\"Logout\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<div class=\"sponsor-div\">\r\n");
      out.write("\t\t<img\r\n");
      out.write("\t\t\tsrc=\"https://static.wixstatic.com/media/6fddee_b56667a4759c4b8984c877fa4752ba81.gif\"\r\n");
      out.write("\t\t\talt=\"Sponsor\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"partner-div\">\r\n");
      out.write("\t\t<img\r\n");
      out.write("\t\t\tsrc=\"http://bwfworldchampionships.com/wp-content/uploads/2014/07/BWF_logo_holding_device1.jpg\"\r\n");
      out.write("\t\t\talt=\"Partner\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
/*
		Locale aLocale = new Locale("en", "US");
		Locale frLocale = new Locale("fr", "FR");
		Locale dLocale =Locale.getDefault();
		ResourceBundle messages = ResourceBundle.getBundle("MessagesBundle", dLocale);
		out.println("<h2>" + messages.getString("greetings") + " from  " + dLocale.getDisplayCountry() + 
				"</h2>");*/
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_fmt_005fsetBundle_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_fmt_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<br />\r\n");
      out.write("\t<script src=\"../js/home.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fsetBundle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setBundle
    org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag _jspx_th_fmt_005fsetBundle_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag) _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag.class);
    boolean _jspx_th_fmt_005fsetBundle_005f0_reused = false;
    try {
      _jspx_th_fmt_005fsetBundle_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fsetBundle_005f0.setParent(null);
      // /pages/home.jsp(76,1) name = basename type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fsetBundle_005f0.setBasename("com.zilker.properties.MessagesBundle");
      // /pages/home.jsp(76,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fsetBundle_005f0.setVar("lang");
      int _jspx_eval_fmt_005fsetBundle_005f0 = _jspx_th_fmt_005fsetBundle_005f0.doStartTag();
      if (_jspx_th_fmt_005fsetBundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody.reuse(_jspx_th_fmt_005fsetBundle_005f0);
      _jspx_th_fmt_005fsetBundle_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fsetBundle_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fsetBundle_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f0_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f0.setParent(null);
      // /pages/home.jsp(77,1) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f0.setKey("greetings");
      // /pages/home.jsp(77,1) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f0.setBundle((javax.servlet.jsp.jstl.fmt.LocalizationContext) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lang}", javax.servlet.jsp.jstl.fmt.LocalizationContext.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      _jspx_th_fmt_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f0_reused);
    }
    return false;
  }
}
